### ISSUE TITLE
Starting test run on Windows results in "Illegal character in opaque part"

### ISSUE THREAD

**Issue by jonherrmann** [interactive-instruments/etf-webapp#20]
Starting test run on Windows results in "Illegal character in opaque part":

```
2016-06-01 08:15:54.361 [http-apr-8080-exec-8] ERROR d.i.e.w.c.GlobalDefaultExceptionHandler - Last action: http://server:8080/etf-webapp/testruns/start
de.interactive_instruments.exceptions.StoreException: Initialization Failed. Illegal character in opaque part at index 2: D:\Programme\Apache Software Foundation\Tomcat 8.0\webapps\etf-webapp\WEB-INF\etf\ds\appendices3cca79c5-9fb3-441f-b37c-789864e8b9ae/appendices/
	at de.interactive_instruments.etf.dal.basex.dao.BasexTestReportDao.createFactory(BasexTestReportDao.java:147) ~[etf-bsxds-1.0.7.1.jar:1.0.7.1]
	at de.interactive_instruments.etf.dal.basex.dao.BasexTestReportDao.create(BasexTestReportDao.java:165) ~[etf-bsxds-1.0.7.1.jar:1.0.7.1]
	at de.interactive_instruments.etf.webapp.controller.TestReportController.createReport(TestReportController.java:110) ~[classes/:1.0.7.3]
	at de.interactive_instruments.etf.webapp.controller.TestRunController.start(TestRunController.java:347) ~[classes/:1.0.7.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
```

**Comment by jonherrmann** [comment]
Fixed in ii-commons 1.2.8
